restaurant_search_homepage:
    path:     /
    defaults: { _controller: RestaurantSearchBundle:Default:index }
restaurant_search_about:
    path:     /about/
    defaults: { _controller: RestaurantSearchBundle:Default:about }